### PR TITLE
Removed Toast and added Dialog

### PR DESCRIPTION
**Pull request by aneeshgupta25**

### CODE REVIEW

**Comment by aneeshgupta25** [comment]
Closes #9

**Comment by aneeshgupta25** [comment]
Dialog


I have uploaded this screenshot for your reference.

**Review by pratyaksh1610 — CHANGES_REQUESTED** [review]
Please add some margin between the points and fix the alignment to make it look good.

**Comment by aneeshgupta25** [comment]
@pratyaksh1610 , I have updated the dialog.. Kindly have a look

**Comment by aneeshgupta25** [comment]
dialog_update
Here's the ss..

**Comment by aneeshgupta25** [comment]
Successfully accepting this PR would close Issue-9.

**Pull request merged**
